# -*- coding: utf-8 -*-

from testcases.test_login import TestLoginPage
from testcases.test_logout import TestLogout
from testcases.test_switch_subsystem import TestSwitchSubsystem
from testcases.test_date import TestDate
from testcases.test_task_management import TestSearchTask
from pageobjects.components.driver import Browser
import testrunner

if __name__ == '__main__':
    tests = []
    test_runner = testrunner.TestRunner()
    tests.append(test_runner.load_test(TestLoginPage))
    tests.append(test_runner.load_test(TestSwitchSubsystem))
    #tests.append(test_runner.load_test(TestDate))
    tests.append(test_runner.load_test(TestSearchTask))
    tests.append(test_runner.load_test(TestLogout))

    test_runner.add_tests(tests)
    test_runner.run_tests()

    Browser().close_driver()


    """
        for test_result in test_runner.test_results:
        print(test_result)

        testcases = testrunner.make_unittest_testcases()
        print(testcases)
    
    
       suite = unittest.TestSuite()
        suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestLoginPage))
        suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestLogout))

        with open('htmlreport.html', 'w') as f:
            runner = HTMLTestRunner(
                stream=f,
                title='uiautotest report',
                description='generated by htmltestrunner.',
                verbosity=2
            )
            runner.run(suite)
        Browser().close_driver()
        """

