# -*- coding: utf-8 -*-

from testsuites.task_management_testsuite import TestSearchTask
import testrunner

if __name__ == '__main__':
    tests = []
    test_runner = testrunner.TestRunner()
    tests.append(test_runner.load_test(TestSearchTask))

    test_runner.add_tests(tests)
    test_runner.run_tests()


    """
        for test_result in test_runner.test_results:
        print(test_result)

        testsuites = testrunner.make_unittest_testcases()
        print(testsuites)
    
    
       suite = unittest.TestSuite()
        suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestLoginPage))
        suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestLogout))

        with open('htmlreport.html', 'w') as f:
            runner = HTMLTestRunner(
                stream=f,
                title='uiautotest report',
                description='generated by htmltestrunner.',
                verbosity=2
            )
            runner.run(suite)
        Browser().close_driver()
        """

